<?php
declare(strict_types=1);
function admin_can(array $user, string $capability): bool { $map=['administrator'=>['*'],'seo_manager'=>['posts','publish','categories'],'editor'=>['posts'],'author'=>['own_posts']]; return in_array('*',$map[$user['role']]??[],true)||in_array($capability,$map[$user['role']]??[],true); }
function require_capability(array $user,string $capability): void { if(!admin_can($user,$capability)){http_response_code(403);exit('You do not have permission for this action.');} }
function clean_text(string $value,int $limit=10000): string { return mb_substr(trim(strip_tags($value,'<p><br><strong><em><ul><ol><li><h2><h3><a>')) ,0,$limit); }
function audit(PDO $db,array $user,string $action,string $type,int $id,array $details=[]): void { $db->prepare('INSERT INTO audit_logs(user_id,action,entity_type,entity_id,details,ip_address,user_agent) VALUES(?,?,?,?,?,?,?)')->execute([$user['id'],$action,$type,$id,json_encode($details),$_SERVER['REMOTE_ADDR']??null,mb_substr($_SERVER['HTTP_USER_AGENT']??'',0,500)]); }
function post_owner(array $user,array $post): bool { return admin_can($user,'posts') || ((int)$post['author_id']===(int)$user['id'] && $post['status']==='draft'); }
function post_publishable(array $user): bool { return admin_can($user,'publish'); }
function valid_post_status(string $value): string { return in_array($value,['draft','published','archived'],true)?$value:'draft'; }
function safe_image_upload(string $key): ?string { if(empty($_FILES[$key]['tmp_name'])||$_FILES[$key]['error']===UPLOAD_ERR_NO_FILE)return null; $f=$_FILES[$key];$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];if($f['error']!==UPLOAD_ERR_OK||$f['size']>5*1024*1024)throw new RuntimeException('Image upload failed or exceeds 5 MB.');$mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);$ext=strtolower(pathinfo($f['name'],PATHINFO_EXTENSION));if(!isset($allowed[$mime])||!in_array($ext,['jpg','jpeg','png','webp'],true))throw new RuntimeException('Only JPG, PNG, and WEBP images are allowed.');$dir=__DIR__.'/../assets/uploads/blog';if(!is_dir($dir)&&!mkdir($dir,0755,true))throw new RuntimeException('Upload folder is unavailable.');$name=bin2hex(random_bytes(16)).'.'.$allowed[$mime];if(!move_uploaded_file($f['tmp_name'],$dir.'/'.$name))throw new RuntimeException('Image could not be stored.');return '/assets/uploads/blog/'.$name; }
